// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_sdk`, `pending_lock`, `sdk_lock`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OnboardingState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Returns the current shard upload progress (current, total).
/// Poll this from Dart during uploads for real-time shard-level progress.
ShardProgressInfo getShardProgress() =>
    RustLib.instance.api.crateApiGetShardProgress();

/// Request a new app connection with the indexer.
/// Returns an approval URL the user must open in a browser.
/// After showing the URL, call [wait_for_approval]. If that fails with a
/// network error, call this again to get a fresh URL and retry.
Future<String> requestConnection() =>
    RustLib.instance.api.crateApiRequestConnection();

/// Waits for the user to approve the connection in the browser.
/// Returns Ok(()) when approved. Returns Err on network failure or expiry —
/// in that case call [request_connection] again to get a fresh URL and retry.
Future<void> waitForApproval() =>
    RustLib.instance.api.crateApiWaitForApproval();

/// Complete registration after [wait_for_approval] succeeds.
/// Returns the hex-encoded App Key.
Future<String> registerWithPhrase({required String recoveryPhrase}) => RustLib
    .instance
    .api
    .crateApiRegisterWithPhrase(recoveryPhrase: recoveryPhrase);

/// Generate a new BIP-39 12-word recovery phrase.
String generateRecoveryPhrase() =>
    RustLib.instance.api.crateApiGenerateRecoveryPhrase();

/// Validate a BIP-39 recovery phrase. Returns Ok(()) or an error message.
void validatePhrase({required String phrase}) =>
    RustLib.instance.api.crateApiValidatePhrase(phrase: phrase);

/// Reconnect to the indexer using a previously stored App Key (hex-encoded).
/// Must be called at app startup before any object operations.
Future<void> connect({required String appKeyHex}) =>
    RustLib.instance.api.crateApiConnect(appKeyHex: appKeyHex);

/// Upload data with metadata, pin the object, and return its hex object ID.
Future<String> uploadAndPin({
  required List<int> data,
  required String metadataJson,
}) => RustLib.instance.api.crateApiUploadAndPin(
  data: data,
  metadataJson: metadataJson,
);

/// Upload multiple small objects packed into shared slabs for efficiency.
/// Returns a list of hex object IDs in the same order as the input items.
///
/// Uses reduced shard counts (3 data + 9 parity = 12 total) for faster
/// uploads while maintaining 4× redundancy and >99.99% recovery probability.
/// Shard-level progress is available via [get_shard_progress].
Future<List<String>> uploadPackedAndPin({required List<UploadItem> items}) =>
    RustLib.instance.api.crateApiUploadPackedAndPin(items: items);

/// Download an object by hex ID. Returns the data bytes, metadata JSON, and size.
Future<SiaObject> downloadObject({required String objectId}) =>
    RustLib.instance.api.crateApiDownloadObject(objectId: objectId);

/// Update metadata on a pinned object without re-uploading data.
Future<void> updateObjectMetadata({
  required String objectId,
  required String metadataJson,
}) => RustLib.instance.api.crateApiUpdateObjectMetadata(
  objectId: objectId,
  metadataJson: metadataJson,
);

/// Delete a pinned object and prune unreferenced slabs.
Future<void> deleteObject({required String objectId}) =>
    RustLib.instance.api.crateApiDeleteObject(objectId: objectId);

/// Fetch object events for incremental sync.
/// Pass an empty cursor on first call.  Returns events and whether more pages exist.
Future<SyncResult> listObjects({
  required String cursorAfter,
  required String cursorId,
  required int limit,
}) => RustLib.instance.api.crateApiListObjects(
  cursorAfter: cursorAfter,
  cursorId: cursorId,
  limit: limit,
);

/// Share an object — returns a time-limited public URL.
Future<String> shareObject({
  required String objectId,
  required int expiresHours,
}) => RustLib.instance.api.crateApiShareObject(
  objectId: objectId,
  expiresHours: expiresHours,
);

/// Delete all pinned objects from the connected account.
/// Pages through all object events and deletes each one.
/// Returns the number of objects deleted.
Future<int> deleteAllObjects() =>
    RustLib.instance.api.crateApiDeleteAllObjects();

class ShardProgressInfo {
  final int current;
  final int total;

  const ShardProgressInfo({required this.current, required this.total});

  @override
  int get hashCode => current.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShardProgressInfo &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          total == other.total;
}

class SiaObject {
  final String objectId;
  final Uint8List data;
  final String metadataJson;
  final BigInt size;

  const SiaObject({
    required this.objectId,
    required this.data,
    required this.metadataJson,
    required this.size,
  });

  @override
  int get hashCode =>
      objectId.hashCode ^ data.hashCode ^ metadataJson.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SiaObject &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          data == other.data &&
          metadataJson == other.metadataJson &&
          size == other.size;
}

class SiaObjectEvent {
  final String objectId;
  final bool deleted;
  final String? metadataJson;
  final String updatedAt;

  const SiaObjectEvent({
    required this.objectId,
    required this.deleted,
    this.metadataJson,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      objectId.hashCode ^
      deleted.hashCode ^
      metadataJson.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SiaObjectEvent &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          deleted == other.deleted &&
          metadataJson == other.metadataJson &&
          updatedAt == other.updatedAt;
}

class SyncResult {
  final List<SiaObjectEvent> events;
  final bool hasMore;

  const SyncResult({required this.events, required this.hasMore});

  @override
  int get hashCode => events.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResult &&
          runtimeType == other.runtimeType &&
          events == other.events &&
          hasMore == other.hasMore;
}

class UploadItem {
  final Uint8List data;
  final String metadataJson;

  const UploadItem({required this.data, required this.metadataJson});

  @override
  int get hashCode => data.hashCode ^ metadataJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadItem &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          metadataJson == other.metadataJson;
}
