// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -2026650338;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'sical_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiConnect({required String appKeyHex});

  Future<int> crateApiDeleteAllObjects();

  Future<void> crateApiDeleteObject({required String objectId});

  Future<SiaObject> crateApiDownloadObject({required String objectId});

  String crateApiGenerateRecoveryPhrase();

  ShardProgressInfo crateApiGetShardProgress();

  Future<SyncResult> crateApiListObjects({
    required String cursorAfter,
    required String cursorId,
    required int limit,
  });

  Future<String> crateApiRegisterWithPhrase({required String recoveryPhrase});

  Future<String> crateApiRequestConnection();

  Future<String> crateApiShareObject({
    required String objectId,
    required int expiresHours,
  });

  Future<void> crateApiUpdateObjectMetadata({
    required String objectId,
    required String metadataJson,
  });

  Future<String> crateApiUploadAndPin({
    required List<int> data,
    required String metadataJson,
  });

  Future<List<String>> crateApiUploadPackedAndPin({
    required List<UploadItem> items,
  });

  void crateApiValidatePhrase({required String phrase});

  Future<void> crateApiWaitForApproval();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiConnect({required String appKeyHex}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appKeyHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConnectConstMeta,
        argValues: [appKeyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectConstMeta =>
      const TaskConstMeta(debugName: "connect", argNames: ["appKeyHex"]);

  @override
  Future<int> crateApiDeleteAllObjects() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeleteAllObjectsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteAllObjectsConstMeta =>
      const TaskConstMeta(debugName: "delete_all_objects", argNames: []);

  @override
  Future<void> crateApiDeleteObject({required String objectId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(objectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeleteObjectConstMeta,
        argValues: [objectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteObjectConstMeta =>
      const TaskConstMeta(debugName: "delete_object", argNames: ["objectId"]);

  @override
  Future<SiaObject> crateApiDownloadObject({required String objectId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(objectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sia_object,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDownloadObjectConstMeta,
        argValues: [objectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadObjectConstMeta =>
      const TaskConstMeta(debugName: "download_object", argNames: ["objectId"]);

  @override
  String crateApiGenerateRecoveryPhrase() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateRecoveryPhraseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateRecoveryPhraseConstMeta =>
      const TaskConstMeta(debugName: "generate_recovery_phrase", argNames: []);

  @override
  ShardProgressInfo crateApiGetShardProgress() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_shard_progress_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetShardProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetShardProgressConstMeta =>
      const TaskConstMeta(debugName: "get_shard_progress", argNames: []);

  @override
  Future<SyncResult> crateApiListObjects({
    required String cursorAfter,
    required String cursorId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cursorAfter, serializer);
          sse_encode_String(cursorId, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiListObjectsConstMeta,
        argValues: [cursorAfter, cursorId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListObjectsConstMeta => const TaskConstMeta(
    debugName: "list_objects",
    argNames: ["cursorAfter", "cursorId", "limit"],
  );

  @override
  Future<String> crateApiRegisterWithPhrase({required String recoveryPhrase}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(recoveryPhrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRegisterWithPhraseConstMeta,
        argValues: [recoveryPhrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRegisterWithPhraseConstMeta => const TaskConstMeta(
    debugName: "register_with_phrase",
    argNames: ["recoveryPhrase"],
  );

  @override
  Future<String> crateApiRequestConnection() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRequestConnectionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestConnectionConstMeta =>
      const TaskConstMeta(debugName: "request_connection", argNames: []);

  @override
  Future<String> crateApiShareObject({
    required String objectId,
    required int expiresHours,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(objectId, serializer);
          sse_encode_u_32(expiresHours, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiShareObjectConstMeta,
        argValues: [objectId, expiresHours],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiShareObjectConstMeta => const TaskConstMeta(
    debugName: "share_object",
    argNames: ["objectId", "expiresHours"],
  );

  @override
  Future<void> crateApiUpdateObjectMetadata({
    required String objectId,
    required String metadataJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(objectId, serializer);
          sse_encode_String(metadataJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpdateObjectMetadataConstMeta,
        argValues: [objectId, metadataJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateObjectMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "update_object_metadata",
        argNames: ["objectId", "metadataJson"],
      );

  @override
  Future<String> crateApiUploadAndPin({
    required List<int> data,
    required String metadataJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_String(metadataJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUploadAndPinConstMeta,
        argValues: [data, metadataJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUploadAndPinConstMeta => const TaskConstMeta(
    debugName: "upload_and_pin",
    argNames: ["data", "metadataJson"],
  );

  @override
  Future<List<String>> crateApiUploadPackedAndPin({
    required List<UploadItem> items,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_upload_item(items, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUploadPackedAndPinConstMeta,
        argValues: [items],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUploadPackedAndPinConstMeta => const TaskConstMeta(
    debugName: "upload_packed_and_pin",
    argNames: ["items"],
  );

  @override
  void crateApiValidatePhrase({required String phrase}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiValidatePhraseConstMeta,
        argValues: [phrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidatePhraseConstMeta =>
      const TaskConstMeta(debugName: "validate_phrase", argNames: ["phrase"]);

  @override
  Future<void> crateApiWaitForApproval() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaitForApprovalConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaitForApprovalConstMeta =>
      const TaskConstMeta(debugName: "wait_for_approval", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SiaObjectEvent> dco_decode_list_sia_object_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sia_object_event).toList();
  }

  @protected
  List<UploadItem> dco_decode_list_upload_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_upload_item).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ShardProgressInfo dco_decode_shard_progress_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ShardProgressInfo(
      current: dco_decode_u_32(arr[0]),
      total: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  SiaObject dco_decode_sia_object(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SiaObject(
      objectId: dco_decode_String(arr[0]),
      data: dco_decode_list_prim_u_8_strict(arr[1]),
      metadataJson: dco_decode_String(arr[2]),
      size: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  SiaObjectEvent dco_decode_sia_object_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SiaObjectEvent(
      objectId: dco_decode_String(arr[0]),
      deleted: dco_decode_bool(arr[1]),
      metadataJson: dco_decode_opt_String(arr[2]),
      updatedAt: dco_decode_String(arr[3]),
    );
  }

  @protected
  SyncResult dco_decode_sync_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SyncResult(
      events: dco_decode_list_sia_object_event(arr[0]),
      hasMore: dco_decode_bool(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UploadItem dco_decode_upload_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return UploadItem(
      data: dco_decode_list_prim_u_8_strict(arr[0]),
      metadataJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SiaObjectEvent> sse_decode_list_sia_object_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SiaObjectEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sia_object_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<UploadItem> sse_decode_list_upload_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <UploadItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_upload_item(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ShardProgressInfo sse_decode_shard_progress_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_current = sse_decode_u_32(deserializer);
    var var_total = sse_decode_u_32(deserializer);
    return ShardProgressInfo(current: var_current, total: var_total);
  }

  @protected
  SiaObject sse_decode_sia_object(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_objectId = sse_decode_String(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_metadataJson = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    return SiaObject(
      objectId: var_objectId,
      data: var_data,
      metadataJson: var_metadataJson,
      size: var_size,
    );
  }

  @protected
  SiaObjectEvent sse_decode_sia_object_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_objectId = sse_decode_String(deserializer);
    var var_deleted = sse_decode_bool(deserializer);
    var var_metadataJson = sse_decode_opt_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return SiaObjectEvent(
      objectId: var_objectId,
      deleted: var_deleted,
      metadataJson: var_metadataJson,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  SyncResult sse_decode_sync_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_events = sse_decode_list_sia_object_event(deserializer);
    var var_hasMore = sse_decode_bool(deserializer);
    return SyncResult(events: var_events, hasMore: var_hasMore);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UploadItem sse_decode_upload_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_metadataJson = sse_decode_String(deserializer);
    return UploadItem(data: var_data, metadataJson: var_metadataJson);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sia_object_event(
    List<SiaObjectEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sia_object_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_upload_item(
    List<UploadItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_upload_item(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_shard_progress_info(
    ShardProgressInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.current, serializer);
    sse_encode_u_32(self.total, serializer);
  }

  @protected
  void sse_encode_sia_object(SiaObject self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.objectId, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_String(self.metadataJson, serializer);
    sse_encode_u_64(self.size, serializer);
  }

  @protected
  void sse_encode_sia_object_event(
    SiaObjectEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.objectId, serializer);
    sse_encode_bool(self.deleted, serializer);
    sse_encode_opt_String(self.metadataJson, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_sync_result(SyncResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_sia_object_event(self.events, serializer);
    sse_encode_bool(self.hasMore, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_upload_item(UploadItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_String(self.metadataJson, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
